// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8vg21vRcClGzNe4GfrL3lL-XvG41A9ik',
    appId: '1:152931878057:web:72dcec80b0914b9051d5b8',
    messagingSenderId: '152931878057',
    projectId: 'chatapptask-43b29',
    authDomain: 'chatapptask-43b29.firebaseapp.com',
    databaseURL: 'https://chatapptask-43b29-default-rtdb.firebaseio.com',
    storageBucket: 'chatapptask-43b29.appspot.com',
    measurementId: 'G-3K8RBHD5XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKj665ysSBb8M3amfUNIgIrivhHeH6GHA',
    appId: '1:152931878057:android:c6fee677c09d7ebf51d5b8',
    messagingSenderId: '152931878057',
    projectId: 'chatapptask-43b29',
    databaseURL: 'https://chatapptask-43b29-default-rtdb.firebaseio.com',
    storageBucket: 'chatapptask-43b29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD51n4myN_u_BbWiDXJI2ZpiiWr7V-00tQ',
    appId: '1:152931878057:ios:7b9c666d76ff667651d5b8',
    messagingSenderId: '152931878057',
    projectId: 'chatapptask-43b29',
    databaseURL: 'https://chatapptask-43b29-default-rtdb.firebaseio.com',
    storageBucket: 'chatapptask-43b29.appspot.com',
    iosBundleId: 'com.example.Anshu.chatAppTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD51n4myN_u_BbWiDXJI2ZpiiWr7V-00tQ',
    appId: '1:152931878057:ios:7b9c666d76ff667651d5b8',
    messagingSenderId: '152931878057',
    projectId: 'chatapptask-43b29',
    databaseURL: 'https://chatapptask-43b29-default-rtdb.firebaseio.com',
    storageBucket: 'chatapptask-43b29.appspot.com',
    iosBundleId: 'com.example.Anshu.chatAppTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8vg21vRcClGzNe4GfrL3lL-XvG41A9ik',
    appId: '1:152931878057:web:2a324479c31850ab51d5b8',
    messagingSenderId: '152931878057',
    projectId: 'chatapptask-43b29',
    authDomain: 'chatapptask-43b29.firebaseapp.com',
    databaseURL: 'https://chatapptask-43b29-default-rtdb.firebaseio.com',
    storageBucket: 'chatapptask-43b29.appspot.com',
    measurementId: 'G-V1JHNQ4G7S',
  );

}